Repository kartoza/sawps, pull requests merged in 2023-09, with the labels that each got.

#903 Fixes for profile pages
  django_project/frontend/static/js/modernizr-custom.js
  django_project/frontend/templates/allauth_2fa/backup_tokens.html
  django_project/frontend/templates/base.html
  django_project/frontend/templates/profile.html
  django_project/frontend/templates/profile_config_base.html
  django_project/frontend/templates/reminders.html
  django_project/stakeholder/migrations/0011_userprofile_allowing_sanbi_to_expose_data_and_more.py
  django_project/stakeholder/models.py
  django_project/stakeholder/test_profile.py
  django_project/stakeholder/views.py
Labels: Size: 5, Fix

#911 Fixes for chart layouts
  django_project/frontend/src/containers/MainPage/Metrics/ActivityDonutChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/AgeGroupBarChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/DensityBarChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/index.tsx
Labels: Size: 2, Fix

#921 patch: use id instead to prevent simpleLazy object error
  django_project/frontend/tests/test_2fa_view.py
  django_project/frontend/views/totp_device.py
Labels: Size: 1, Fix

#803 integration PDF download
  django_project/frontend/package-lock.json
  django_project/frontend/package.json
  django_project/frontend/src/containers/MainPage/Metrics/ActivityDonutChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/DensityBarChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/PopulationCategoryChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/PropertyAvailable.tsx
  django_project/frontend/src/containers/MainPage/Metrics/PropertyType.tsx
  django_project/frontend/src/containers/MainPage/Metrics/SpeciesLineChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/index.scss
  django_project/frontend/src/containers/MainPage/Metrics/index.tsx
  django_project/frontend/tests/test_metrics.py
  django_project/population_data/test_population_data_models.py
Labels: Size: 5, Pillar 3: wireframe, Implementation

#924 Rename tab values with names in url
  django_project/frontend/src/containers/MainPage/MainPage.tsx
  django_project/frontend/tests/test_map_view.py
  django_project/frontend/urls.py
  django_project/frontend/views/map.py
Labels: Size: 2, Fix

#917 Fix-typography
  django_project/frontend/src/containers/MainPage/Metrics/ChartCard.tsx
Labels: Size: 1, Fix

#920 Organisations page
  django_project/frontend/api_views/map.py
  django_project/frontend/api_views/property.py
  django_project/frontend/templates/navibar.html
  django_project/frontend/templates/organisations.html
  django_project/frontend/templates/profile_config_base.html
  django_project/frontend/tests/base_view.py
  django_project/frontend/tests/test_home_view.py
  django_project/frontend/tests/test_map.py
  django_project/frontend/tests/test_organisations.py
  django_project/frontend/tests/test_property.py
  django_project/frontend/tests/test_users_view.py
  django_project/frontend/urls.py
  django_project/frontend/utils/organisation.py
  django_project/frontend/views/base_view.py
  django_project/frontend/views/organisations.py
  django_project/frontend/views/switch_organisation.py
  django_project/frontend/views/users.py
  django_project/stakeholder/migrations/0012_userprofile_current_organisation.py
  django_project/stakeholder/models.py
  django_project/stakeholder/test_profile.py
  django_project/stakeholder/test_view.py
  django_project/stakeholder/views.py
Labels: Size: 5, Fix

#908 National report pdf page 2
  django_project/frontend/api_views/national_statistic.py
  django_project/frontend/serializers/national_statistics.py
  django_project/frontend/src/components/PdfReport/LineChart.tsx
  django_project/frontend/src/components/PdfReport/PyramidChart.tsx
  django_project/frontend/src/components/PdfReport/SecondPageContainer.tsx
  django_project/frontend/src/components/PdfReport/generateChartImage.tsx
  django_project/frontend/src/components/PdfReport/index.scss
  django_project/frontend/src/components/PdfReport/index.tsx
  django_project/frontend/src/components/PdfReport/logoImage.d.ts
  django_project/frontend/tests/test_national_statistics.py
Labels: Size: 8, Implementation

#936 Tinashechiraya patch 4
  django_project/frontend/utils/organisation.py
  django_project/frontend/views/base_view.py
  django_project/sawps/tests/test_activate_account.py
  django_project/sawps/tests/test_user.py
  django_project/sawps/views.py
Labels: Size: 1, Fix

#941 Tinashechiraya patch 5
  django_project/frontend/api_views/data_table.py
  django_project/frontend/api_views/metrics.py
  django_project/frontend/tests/test_data_table.py
  django_project/frontend/tests/test_metrics.py
Labels: Size: 1, Fix

#882 Natinal report pdf page 3
  django_project/frontend/api_views/national_statistic.py
  django_project/frontend/serializers/national_statistics.py
  django_project/frontend/src/components/PdfReport/DonughtChartForPdf.tsx
  django_project/frontend/src/components/PdfReport/PopulationCategoryChart.tsx
  django_project/frontend/src/components/PdfReport/ThirdPageContainer.tsx
  django_project/frontend/src/components/PdfReport/generateChartImage.tsx
  django_project/frontend/src/components/PdfReport/index.scss
  django_project/frontend/src/components/PdfReport/index.tsx
  django_project/frontend/src/components/PdfReport/logoImage.d.ts
  django_project/frontend/tests/test_national_statistics.py
  django_project/frontend/urls.py
Labels: Size: 8, Implementation

#927 Fix firefox browser issues
  django_project/frontend/static/fontawesome-free-6.4.2-web/LICENSE.txt
  django_project/frontend/static/fontawesome-free-6.4.2-web/css/all.css
  django_project/frontend/static/fontawesome-free-6.4.2-web/css/all.min.css
  django_project/frontend/static/fontawesome-free-6.4.2-web/js/all.js
  django_project/frontend/static/fontawesome-free-6.4.2-web/js/all.min.js
  django_project/frontend/templates/base.html
  django_project/frontend/templates/reminders.html
Labels: Size: 1, draft, Fix

#939 Styling fixes
  django_project/frontend/static/css/style.css
  django_project/frontend/templates/allauth_2fa/backup_tokens.html
  django_project/frontend/templates/navibar.html
  django_project/frontend/templates/organisations.html
  django_project/frontend/templates/profile.html
  django_project/frontend/templates/profile_config_base.html
  django_project/frontend/templates/reminders.html
  django_project/frontend/templates/users.html
Labels: Size: 1, Fix

#945 Tinashechiraya patch 6
  django_project/frontend/static/fontawesome-free-6.4.2-web/webfonts/fa-brands-400.ttf
  django_project/frontend/static/fontawesome-free-6.4.2-web/webfonts/fa-brands-400.woff2
  django_project/frontend/static/fontawesome-free-6.4.2-web/webfonts/fa-regular-400.ttf
  django_project/frontend/static/fontawesome-free-6.4.2-web/webfonts/fa-regular-400.woff2
  django_project/frontend/static/fontawesome-free-6.4.2-web/webfonts/fa-solid-900.ttf
  django_project/frontend/static/fontawesome-free-6.4.2-web/webfonts/fa-solid-900.woff2
  django_project/frontend/static/fontawesome-free-6.4.2-web/webfonts/fa-v4compatibility.ttf
  django_project/frontend/static/fontawesome-free-6.4.2-web/webfonts/fa-v4compatibility.woff2
Labels: Size: 1, Fix

#948 Fix property list API
  django_project/frontend/api_views/property.py
Labels: Size: 1, Fix

#951 Added spatial models
  django_project/frontend/admin.py
  django_project/frontend/migrations/0015_spatialdatamodel_spatialdatavaluemodel.py
  django_project/frontend/models/spatial.py
Labels: Size: 2, Data Model

#952 Tinashechiraya patch 7
  django_project/frontend/templates/account/login.html
  django_project/frontend/templates/allauth_2fa/backup_tokens.html
  django_project/frontend/templates/organisations.html
  django_project/frontend/templates/reminders.html
  django_project/stakeholder/test_view.py
  django_project/stakeholder/views.py
Labels: Size: 1, Fix

#959 patch: adjust page title
  django_project/frontend/templates/help.html
Labels: Size: 1, Fix

#884 National report pdf page 4
  django_project/frontend/api_views/national_statistic.py
  django_project/frontend/src/components/PdfReport/DonughtChartForPdf1.tsx
  django_project/frontend/src/components/PdfReport/DonughtChartForPdf2.tsx
  django_project/frontend/src/components/PdfReport/FourthPageContainer.tsx
  django_project/frontend/src/components/PdfReport/generateChartImage.tsx
  django_project/frontend/src/components/PdfReport/index.scss
  django_project/frontend/tests/test_national_statistics.py
  django_project/frontend/urls.py
Labels: Size: 8, Implementation

#950 Update data-table
  django_project/activity/factories.py
  django_project/activity/tests.py
  django_project/frontend/api_views/data_table.py
  django_project/frontend/filters/data_table.py
  django_project/frontend/serializers/data_table.py
  django_project/frontend/serializers/property.py
  django_project/frontend/src/containers/MainPage/Data/index.scss
  django_project/frontend/src/containers/MainPage/Data/index.tsx
  django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
  django_project/frontend/src/reducers/SpeciesFilter.ts
  django_project/frontend/static/images/InfoIcon.png
  django_project/frontend/static_mapping.py
  django_project/frontend/tests/test_data_table.py
  django_project/frontend/urls.py
  django_project/frontend/utils/data_table.py
  django_project/population_data/serializers.py
  django_project/species/serializers.py
Labels: Size: 13, Implementation, draft

#958 Tinashechiraya patch 8
  django_project/frontend/src/containers/MainPage/MainPage.tsx
  django_project/frontend/templates/account/login.html
  django_project/frontend/templates/navibar.html
  django_project/frontend/templates/profile.html
  django_project/frontend/templates/reminders.html
  django_project/frontend/tests/test_map_view.py
  django_project/frontend/urls.py
  django_project/frontend/views/map.py
Labels: Size: 1, Fix

#984 Country level map styles v2
  django_project/frontend/utils/country_level_dark_v2.json
  django_project/frontend/utils/country_level_light_v2.json
  django_project/frontend/utils/map.py
Labels: Size: 1, Fix

#986 patch: use correct value for rows per page #969
  django_project/frontend/views/users.py
Labels: Size: 1, Fix

#980 a user manual entry for the dev team to check out
  docs/src/user/manual/img/profile-picture-upload.png
  docs/src/user/manual/img/profile.png
  docs/src/user/manual/index.md
  docs/src/user/manual/profile-page.md
  docs/src/user/manual/site-pages.md
Labels: documentation

#985 styling fixes
  django_project/frontend/templates/profile_config_base.html
  django_project/frontend/templates/reminders.html
Labels: Size: 1, Fix

#987 patch: prevent fields overlaping on form #956
  django_project/frontend/src/containers/OnlineFormPage/Forms/SpeciesDetail.tsx
Labels: Size: 1, Fix

#1003 Feature data table national
  django_project/frontend/api_views/data_table.py
  django_project/frontend/src/containers/MainPage/Data/index.tsx
  django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
  django_project/frontend/static_mapping.py
  django_project/frontend/tests/test_data_table.py
  django_project/frontend/utils/data_table.py
Labels: Size: 13, Implementation

#1009 addition of page to navigation and removal of a dummy file.
  docs/mkdocs-base.yml
  docs/src/user/manual/site-pages.md
Labels: documentation

#981 Update 2fa page and underline titles
  django_project/frontend/templates/allauth_2fa/backup_tokens.html
  django_project/frontend/templates/profile.html
  django_project/frontend/templates/profile_config_base.html
  django_project/frontend/templates/reminders.html
  django_project/frontend/templates/users.html
Labels: Size: 1, Fix

#1000 Styling fixes 1
  django_project/frontend/src/components/LandingPage/LandingPageBanner/LandingPageBannerText/index.tsx
  django_project/frontend/src/containers/MainPage/MainPage.tsx
  django_project/frontend/templates/account/password_change.html
  django_project/frontend/templates/allauth_2fa/backup_tokens.html
  django_project/frontend/templates/organisations.html
  django_project/frontend/templates/reminders.html
  django_project/frontend/views/users.py
Labels: Size: 1, Fix

#1019 Feature data scientist
  django_project/frontend/api_views/data_table.py
  django_project/frontend/api_views/property.py
  django_project/frontend/src/containers/MainPage/Data/index.tsx
  django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
  django_project/frontend/src/reducers/SpeciesFilter.ts
  django_project/frontend/static_mapping.py
  django_project/frontend/tests/test_data_table.py
  django_project/frontend/tests/test_organisations.py
  django_project/frontend/tests/test_property.py
  django_project/species/test_species_models.py
  django_project/species/views.py
  django_project/stakeholder/urls.py
  django_project/stakeholder/views.py
Labels: Size: 8, Implementation

#1026 Fixes for data tab filter
  django_project/frontend/src/containers/MainPage/Metrics/ActivityDonutChart.tsx
  django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
Labels: Size: 2

#1030 Added radio button with collapse
  django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
Labels: Size: 2

#1035 Fix repeating species issue
  django_project/frontend/tests/test_data_table.py
  django_project/frontend/utils/data_table.py
  django_project/species/views.py
Labels: bug, Size: 1

#1032 Year restrictions
  django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
  django_project/frontend/static/images/organisation.png
Labels: bug, Size: 2

#1036 Alpgbetical order
  django_project/frontend/api_views/property.py
  django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
  django_project/species/views.py
  django_project/stakeholder/views.py
Labels: bug, Size: 1

#1031 Added select all option
  django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
Labels: enhancement, Size: 2

#1037 UI fixes
  django_project/frontend/src/components/PdfReport/index.scss
  django_project/frontend/src/containers/MainPage/Data/index.scss
  django_project/frontend/src/containers/MainPage/Metrics/index.scss
  django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
  django_project/frontend/src/containers/MainPage/SideBar/index.scss
  django_project/frontend/static/images/FilterIcon.png
  django_project/frontend/static/images/FilterIcon.svg
  django_project/frontend/static/images/InfoIcon.png
  django_project/frontend/static/images/iconamoon.svg
  django_project/frontend/static/images/organisation.svg
  django_project/frontend/static/images/property.svg
  django_project/frontend/static/images/propertyIcon.png
  django_project/frontend/static/images/species/elephant.png
  django_project/frontend/static/images/species/elephant.svg
  django_project/frontend/static/images/watch.svg
  django_project/frontend/static/images/watchIcon.png
  django_project/frontend/templates/base.html
Labels: bug, Size: 2

#1054 Added search bar on species
  django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
  django_project/frontend/src/containers/MainPage/SideBar/index.scss
Labels: enhancement, Size: 3

#1057 Update organisations page and scrollbar
  django_project/frontend/serializers/stakeholder.py
  django_project/frontend/templates/organisations.html
  django_project/frontend/templates/profile_config_base.html
  django_project/frontend/templates/users.html
  django_project/frontend/tests/test_organisations.py
  django_project/frontend/urls.py
  django_project/frontend/views/organisations.py
  django_project/stakeholder/migrations/0013_remove_userprofile_allowing_sanbi_to_expose_data_and_more.py
  django_project/stakeholder/models.py
  django_project/stakeholder/test_profile.py
Labels: Size: 5, Implementation, Fix

#1056 Fixes for activity report
  django_project/frontend/src/containers/MainPage/Data/index.tsx
  django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
Labels: bug, Size: 1

#1058 Remove badges
  django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
Labels: Size: 1, Implementation

#1059 patch: fix user profile does not exist error
  django_project/frontend/tests/base_view.py
  django_project/frontend/tests/test_home_view.py
  django_project/frontend/views/base_view.py
Labels: Size: 1, Fix

#1061 Main dashboard picture and help page updates
  django_project/frontend/src/components/LandingPage/LandingPageBanner/LandingPageBannerImage/index.tsx
  django_project/frontend/templates/help.html
Labels: Size: 1, Fix

#1067 Enforce user roles on organisations pages
  django_project/frontend/templates/organisations.html
  django_project/frontend/templates/users.html
Labels: Size: 1, Fix

#1070 Make profile pages responsive
  django_project/frontend/templates/allauth_2fa/backup_tokens.html
  django_project/frontend/templates/notifications.html
  django_project/frontend/templates/organisations.html
  django_project/frontend/templates/profile.html
  django_project/frontend/templates/reminders.html
Labels: Size: 1, Fix

#1072 Fix 2fa not authenticating for new users
  deployment/docker/requirements.txt
  django_project/frontend/templates/allauth_2fa/setup.html
  django_project/frontend/templates/base.html
  django_project/frontend/templates/profile_config_base.html
Labels: Size: 2, Fix

#1076 Fix-multiselect-tags
  django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
Labels: Size: 2, Implementation

#1079 Email templates adjustments
  django_project/frontend/templates/emails/invitation_email.html
  django_project/frontend/templates/emails/password_reset.html
  django_project/frontend/templates/emails/reminder_email.html
  django_project/frontend/templates/emails/request_organisation_email.html
Labels: Size: 1, Fix

#1081 patch: adjustments to organisations page #1080
  django_project/frontend/templates/organisations.html
Labels: Size: 1, Fix

#1083 patch: place footer at the bottom of the page on profile page
  django_project/frontend/templates/organisations.html
  django_project/frontend/templates/profile.html
Labels: Size: 1, draft, Fix

#1077 UI fixes for filters for long names.
  django_project/frontend/src/containers/MainPage/Data/index.scss
Labels: Size: 2, Fix

#1098 Species filter by scientific name
  django_project/frontend/filters/metrics.py
  django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
  django_project/frontend/tests/test_data_table.py
  django_project/frontend/tests/test_metrics.py
  django_project/frontend/utils/data_table.py
  django_project/species/serializers.py
  django_project/species/test_species_models.py
  django_project/species/views.py
Labels: Size: 3, Implementation

#1100 Email templates fixes
  django_project/frontend/templates/emails/reminder_email.html
  django_project/frontend/templates/emails/request_organisation_email.html
Labels: Size: 1, Fix

#1101 Rename explore tabs
  django_project/frontend/src/containers/MainPage/MainPage.tsx
  django_project/frontend/tests/test_map_view.py
  django_project/frontend/urls.py
  django_project/frontend/views/map.py
Labels: Size: 1, Fix

#1103 patch: adjust sidebar contents to take full height
  django_project/frontend/src/containers/MainPage/SideBar/index.scss
Labels: Size: 1, Fix

#1104 Population estimate rating
  django_project/frontend/src/containers/OnlineFormPage/Forms/ConfidenceRating.tsx
  django_project/frontend/src/containers/OnlineFormPage/Forms/SpeciesDetail.tsx
  django_project/frontend/src/containers/OnlineFormPage/Forms/index.scss
Labels: Size: 2, Implementation

#1107 Change filter SVGs
  django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
  django_project/frontend/static/images/Clock.svg
  django_project/frontend/static/images/FilterIcon.svg
  django_project/frontend/static/images/Information.svg
  django_project/frontend/static/images/Layers.svg
  django_project/frontend/static/images/Property.svg
  django_project/frontend/static/images/organisation.png
  django_project/frontend/static/images/property.svg
  django_project/frontend/static/images/species/Elephant.svg
  django_project/frontend/static/images/species/elephant.svg
  django_project/frontend/static/images/watch.svg
Labels: Size: 1, Implementation

#1109 Simple filter UI
  django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
  django_project/frontend/src/containers/MainPage/SideBar/index.scss
  django_project/frontend/templates/base.html
  django_project/frontend/templates/navibar.html
Labels: Size: 2, Implementation

#1110 Documentation for data tab and filter panel
  docs/src/user/manual/filters.md
  docs/src/user/manual/img/Explore_filter.png
  docs/src/user/manual/img/Organisation_filter.png
  docs/src/user/manual/img/Property_filter.png
  docs/src/user/manual/img/Report_filter.png
  docs/src/user/manual/img/Spatial_filter.png
  docs/src/user/manual/img/Species_filter.png
  docs/src/user/manual/img/Year_filter.png
  docs/src/user/manual/img/filters.png
  docs/src/user/manual/img/reports.png
  docs/src/user/manual/reports.md
Labels: documentation

#1113 Fix UI issue for half charts
  django_project/frontend/src/components/PdfReport/index.scss
  django_project/frontend/src/containers/MainPage/Metrics/index.scss
  django_project/frontend/src/containers/MainPage/Metrics/index.tsx
Labels: Size: 1, Fix

#1108 Change data tab name to reports
  django_project/frontend/src/containers/MainPage/MainPage.tsx
  django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
Labels: Size: 1, Implementation

#1119 patch: make 2fa environment user friendly #972
  django_project/sawps/admin.py
Labels: Size: 1, Fix

#1123 patch: fix select property or digitise not working #1116
  django_project/frontend/src/containers/MainPage/SideBar/LayerFilterTabs.tsx
Labels: bug, Size: 3

#1133 patch: adjust contact us dialogue #966
  django_project/frontend/templates/contact.html
Labels: Size: 1, Fix

#1134 Remove population category from spatial filter
  django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
Labels: Size: 1

#1121 Show data table to super user
  django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
  django_project/frontend/static/images/organisation.svg
  django_project/frontend/static_mapping.py
Labels: Size: 1, Implementation

#1135 Fix table title cut issue
  django_project/frontend/src/containers/MainPage/index.scss
Labels: Size: 2, Fix

#1142 Struggling to find property
  django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
  django_project/frontend/src/containers/MainPage/SideBar/index.scss
Labels: Size: 5, Fix

#1136 Organisation issue fix
  django_project/frontend/api_views/data_table.py
  django_project/frontend/src/reducers/SpeciesFilter.ts
Labels: bug, Size: 1
