Repository kartoza/sawps, pull requests merged in 2023-10, with the labels that each got.

#1150 Styling improvements
  django_project/frontend/api_views/data_table.py
  django_project/frontend/templates/account/password_change.html
  django_project/frontend/templates/allauth_2fa/backup_tokens.html
  django_project/frontend/templates/base.html
  django_project/frontend/templates/notifications.html
  django_project/frontend/templates/organisations.html
  django_project/frontend/templates/profile.html
  django_project/frontend/templates/reminders.html
  django_project/frontend/templates/users.html
  django_project/frontend/tests/test_map_view.py
  django_project/frontend/urls.py
  django_project/frontend/views/map.py
Labels: Size: 1, Fix

#1156 Add __init__ to species.api_views.upload_species
  django_project/species/api_views/__init__.py
Labels: draft

#1162 Update charts on sidebar panel property information
  django_project/frontend/serializers/metrics.py
  django_project/frontend/src/containers/MainPage/Metrics/ActivityBarChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/SpeciesSideBarLineChart.tsx
  django_project/frontend/src/containers/MainPage/Property/PropertySummary.tsx
  django_project/frontend/templates/account/password_change.html
  django_project/frontend/templates/allauth_2fa/backup_tokens.html
  django_project/frontend/templates/notifications.html
  django_project/frontend/templates/organisations.html
  django_project/frontend/templates/profile.html
  django_project/frontend/templates/reminders.html
Labels: Size: 3, Implementation

#1154 feat: filter property according to organisation #1131
  django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
  django_project/frontend/templates/account/password_change.html
  django_project/frontend/templates/allauth_2fa/backup_tokens.html
  django_project/frontend/templates/base.html
  django_project/frontend/templates/notifications.html
  django_project/frontend/templates/organisations.html
  django_project/frontend/templates/profile.html
  django_project/frontend/templates/reminders.html
Labels: Size: 2, Implementation

#1172 Fixes for help and about page
  django_project/frontend/src/containers/AboutPage/index.scss
  django_project/frontend/src/containers/MainPage/Data/index.scss
  django_project/frontend/static/css/style.css
  django_project/frontend/templates/about.html
  django_project/frontend/templates/help.html
Labels: bug, Implementation

#1179 Tinashechiraya patch 10
  django_project/frontend/api_views/property.py
  django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
  django_project/frontend/tests/test_property.py
  django_project/frontend/urls.py
Labels: Size: 2, Fix

#1178 Chart UI updates
  django_project/frontend/src/containers/MainPage/Metrics/AgeGroupBarChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/AreaAvailableLineChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/DensityBarChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/PopulationCategoryChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/PropertyAvailable.tsx
  django_project/frontend/src/containers/MainPage/Metrics/PropertyType.tsx
  django_project/frontend/src/containers/MainPage/Metrics/SpeciesLineChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/index.scss
  django_project/frontend/src/containers/MainPage/Metrics/index.tsx
Labels: Size: 5, Implementation

#1184 added about page responsive
  django_project/frontend/src/containers/AboutPage/index.scss
  django_project/frontend/static/css/style.css
  django_project/frontend/templates/about.html
  django_project/frontend/templates/contact.html
Labels: bug, Size: 2

#1186 Species population per age group
  django_project/frontend/serializers/metrics.py
  django_project/frontend/src/containers/MainPage/Metrics/AgeGroupBarChart.tsx
  django_project/frontend/tests/test_metrics.py
Labels: Size: 3, Implementation

#1192 Update documentation for filter side panel and for reports tab
  docs/src/user/manual/filters.md
  docs/src/user/manual/img/Activity_filter.png
  docs/src/user/manual/img/Explore_filter.png
  docs/src/user/manual/img/Report_filter.png
  docs/src/user/manual/img/Search_place.png
  docs/src/user/manual/img/Spatial_filter.png
  docs/src/user/manual/img/Species_filter.png
  docs/src/user/manual/img/filters.png
  docs/src/user/manual/img/reports.png
  docs/src/user/manual/reports.md
Labels: documentation, Size: 2

#1198 Species pop age group and total area charts
  django_project/frontend/src/containers/MainPage/Metrics/AgeGroupBarChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/AreaAvailableLineChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/index.tsx
Labels: Size: 5, Implementation

#1206 Documentation for the help page
  docs/src/user/manual/help.md
  docs/src/user/manual/img/Go_to_user_guide.png
  docs/src/user/manual/img/Help.png
  docs/src/user/manual/img/Help_contact_us.png
Labels: documentation, Size: 2

#1204 Fixes horizontal scroll for reports
  django_project/frontend/src/containers/MainPage/Data/index.tsx
  django_project/frontend/src/containers/MainPage/index.scss
Labels: bug, Size: 2

#1197 Fix data table API
  django_project/frontend/utils/data_table.py
Labels: bug, Size: 1

#1207 Species population density per property
  django_project/frontend/api_views/metrics.py
  django_project/frontend/serializers/metrics.py
  django_project/frontend/src/containers/MainPage/Metrics/AreaAvailableLineChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/DensityBarChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/index.tsx
  django_project/frontend/tests/test_metrics.py
Labels: Size: 3, Implementation, draft

#1209 Total property area and UI updates
  django_project/frontend/src/containers/MainPage/Metrics/AgeGroupBarChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/AreaAvailableLineChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/DensityBarChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/PropertyType.tsx
  django_project/frontend/src/containers/MainPage/Metrics/index.tsx
  django_project/frontend/utils/metrics.py
Labels: Size: 3, Implementation

#1183 Fix repeating reports data
  django_project/frontend/api_views/data_table.py
  django_project/frontend/src/containers/MainPage/Data/index.tsx
  django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
  django_project/frontend/tests/test_data_table.py
  django_project/frontend/utils/data_table.py
Labels: Size: 5

#1217 Adjust charts styling
  django_project/frontend/src/containers/MainPage/Metrics/AgeGroupBarChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/AreaAvailableLineChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/PropertyType.tsx
  django_project/frontend/src/containers/MainPage/Metrics/index.tsx
Labels: Size: 1, Fix

#1215 Hide layers tab on charts
  django_project/frontend/src/containers/MainPage/Metrics/AgeGroupBarChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/AreaAvailableLineChart.tsx
  django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
  django_project/frontend/src/containers/MainPage/SideBar/LayerFilterTabs.tsx
Labels: Size: 1, Implementation

#1222 Show names instead of id
  django_project/frontend/utils/data_table.py
Labels: Implementation

#1224 Docs: manual - update profile page and fixed American spellings
  docs/src/developer/guide/design.md
  docs/src/user/manual/user-profile/img/update-password.png
  docs/src/user/manual/user-profile/organisation-page.md
  docs/src/user/manual/user-profile/profile-page.md
  docs/src/user/manual/user-profile/request-organisation.md
Labels: documentation

#1236 Add favicon icon
  django_project/frontend/static/favicon.svg
  django_project/frontend/templates/base.html
Labels: Size: 1, Implementation

#1225 Fixes width for scroll for Reports Table
  django_project/frontend/src/containers/MainPage/Data/index.tsx
  django_project/frontend/src/containers/MainPage/index.scss
Labels: bug, Size: 1

#1238 patch: update chart functionality #1232
  django_project/frontend/src/containers/MainPage/Metrics/AgeGroupBarChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/PropertyType.tsx
Labels: Size: 2, Fix

#1219 Total area available chart
  django_project/frontend/api_views/metrics.py
  django_project/frontend/src/containers/MainPage/Metrics/PropertyAvailable.tsx
  django_project/frontend/src/containers/MainPage/Metrics/PropertyType.tsx
  django_project/frontend/src/containers/MainPage/Metrics/index.tsx
  django_project/frontend/tests/test_metrics.py
  django_project/frontend/utils/metrics.py
Labels: Size: 3, Implementation

#1249 fix-move-pg-element-up
  django_project/frontend/src/containers/AboutPage/index.scss
  django_project/frontend/static/css/style.css
  django_project/frontend/templates/about.html
Labels: bug, Size: 1

#1251 Fixes for forms UI
  django_project/frontend/static/css/style.css
  django_project/frontend/templates/account/login.html
  django_project/frontend/templates/account/logout.html
  django_project/frontend/templates/account/signup.html
  django_project/frontend/templates/allauth_2fa/authenticate.html
Labels: bug, Size: 3

#1114 Refactoring user roles
  django_project/frontend/api_views/data_table.py
  django_project/frontend/api_views/user.py
  django_project/frontend/serializers/user_info.py
  django_project/frontend/src/app/store.ts
  django_project/frontend/src/containers/MainPage/Data/index.tsx
  django_project/frontend/src/containers/MainPage/Map/MapUtility.ts
  django_project/frontend/src/containers/MainPage/Map/index.tsx
  django_project/frontend/src/containers/MainPage/Metrics/index.tsx
  django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
  django_project/frontend/src/services/api.ts
  django_project/frontend/static_mapping.py
  django_project/frontend/templates/base.html
  django_project/frontend/templates/organisations.html
  django_project/frontend/templates/users.html
  django_project/frontend/templatetags/custom_tags.py
  django_project/frontend/tests/test_data_table.py
  django_project/frontend/tests/test_templatetags.py
  django_project/frontend/tests/test_user_roles.py
  django_project/frontend/tests/test_users_view.py
  django_project/frontend/urls.py
  django_project/frontend/utils/data_table.py
  django_project/frontend/utils/user_roles.py
  django_project/frontend/views/users.py
  django_project/stakeholder/models.py
Labels: draft

#1237 Update documentation for filter and reports
  docs/src/user/manual/explore/filters.md
  docs/src/user/manual/explore/img/filters-1.png
  docs/src/user/manual/explore/img/filters-10.png
  docs/src/user/manual/explore/img/filters-2.png
  docs/src/user/manual/explore/img/filters-3.png
  docs/src/user/manual/explore/img/filters-4.png
  docs/src/user/manual/explore/img/filters-5.png
  docs/src/user/manual/explore/img/filters-6.png
  docs/src/user/manual/explore/img/filters-7.png
  docs/src/user/manual/explore/img/filters-8.png
  docs/src/user/manual/explore/img/filters-9.png
  docs/src/user/manual/explore/img/reports-1.png
  docs/src/user/manual/explore/reports.md
Labels: documentation, Size: 1

#1250 Fix density bar chart
  django_project/frontend/serializers/metrics.py
  django_project/frontend/src/containers/MainPage/Metrics/DensityBarChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/PropertyType.tsx
  django_project/frontend/tests/test_metrics.py
Labels: Size: 2, Fix

#1244 fixes collapse issue on property select
  django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
Labels: bug, Size: 1

#1269 Documentation for logout page
  docs/src/user/manual/login-logout/img/logout-1.png
  docs/src/user/manual/login-logout/logout.md
Labels: documentation, Size: 1

#1239 Population size category chart
  django_project/frontend/api_views/metrics.py
  django_project/frontend/api_views/national_statistic.py
  django_project/frontend/src/containers/MainPage/Metrics/PopulationCategoryChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/index.tsx
  django_project/frontend/tests/test_metrics.py
  django_project/frontend/tests/test_national_statistics.py
  django_project/frontend/tests/test_population_categories.py
  django_project/frontend/utils/metrics.py
Labels: Size: 5, charts

#1266 Documentation register page
  docs/src/user/manual/register/img/register-page-1.png
  docs/src/user/manual/register/register-page.md
Labels: documentation, Size: 1

#1271 Population count per province and charts fixes
  django_project/frontend/api_views/metrics.py
  django_project/frontend/src/containers/MainPage/Metrics/AgeGroupBarChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/AreaAvailableLineChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/DensityBarChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/PopulationCategoryChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/PropertyAvailable.tsx
  django_project/frontend/src/containers/MainPage/Metrics/PropertyType.tsx
  django_project/frontend/src/containers/MainPage/Metrics/SpeciesCountPerProvinceChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/index.scss
  django_project/frontend/src/containers/MainPage/Metrics/index.tsx
  django_project/frontend/tests/test_metrics.py
  django_project/frontend/tests/test_population_count_per_province.py
  django_project/frontend/urls.py
  django_project/frontend/utils/metrics.py
Labels: Size: 5, Implementation, charts

#1272 Update help page documentation
  docs/src/user/manual/help-contact.md
  docs/src/user/manual/img/help-contact-1.png
  docs/src/user/manual/img/help-contact-3.png
Labels: documentation, Size: 1

#1267 Documentation for login 2fa page
  docs/src/user/manual/login-logout/img/login-2fa-page-1.png
  docs/src/user/manual/login-logout/login-2fa-page.md
Labels: documentation, Size: 1

#1262 Documentation for login page
  docs/src/user/manual/login-logout/img/login-page-1.png
  docs/src/user/manual/login-logout/login-page.md
Labels: documentation, Size: 1

#1273 Species count per province as percentage
  django_project/frontend/src/containers/MainPage/Metrics/SpeciesCountAsPercentage.tsx
  django_project/frontend/src/containers/MainPage/Metrics/index.tsx
Labels: Size: 3, charts

#1289 Documentation landing page
  docs/src/user/manual/img/landing-page-1.png
  docs/src/user/manual/img/landing-page-2.png
  docs/src/user/manual/img/landing-page-3.png
  docs/src/user/manual/landing-page.md
Labels: documentation, Size: 2

#1304 Add donut charts
  django_project/frontend/api_views/metrics.py
  django_project/frontend/serializers/metrics.py
  django_project/frontend/src/containers/MainPage/Metrics/ActivityCountAsPercentage.tsx
  django_project/frontend/src/containers/MainPage/Metrics/DensityBarChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/PopulationCategoryChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/PopulationEstimateCategory.tsx
  django_project/frontend/src/containers/MainPage/Metrics/PopulationEstimateCategoryAsPercentage.tsx
  django_project/frontend/src/containers/MainPage/Metrics/SpeciesCountAsPercentage.tsx
  django_project/frontend/src/containers/MainPage/Metrics/SpeciesCountPerProvinceChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/TotalCountPerActivity.tsx
  django_project/frontend/src/containers/MainPage/Metrics/index.tsx
  django_project/frontend/tests/test_metrics.py
  django_project/frontend/tests/test_population_estimate_category.py
  django_project/frontend/urls.py
Labels: Size: 5, charts

#1307 Tinashechiraya patch 11
  django_project/frontend/src/containers/MainPage/Metrics/PopulationEstimateCategory.tsx
  django_project/frontend/src/containers/MainPage/Metrics/PopulationEstimateCategoryAsPercentage.tsx
  django_project/frontend/src/containers/MainPage/Metrics/SpeciesCountAsPercentage.tsx
  django_project/frontend/src/containers/MainPage/Metrics/TotalCountPerActivity.tsx
Labels: Size: 1, Fix

#1308 Documentation template upload
  docs/src/user/manual/data-upload/img/template-upload-1.png
  docs/src/user/manual/data-upload/template-upload.md
Labels: documentation, Size: 2

#1319 Charts responsiveness
  django_project/frontend/src/containers/MainPage/Metrics/ActivityCountAsPercentage.tsx
  django_project/frontend/src/containers/MainPage/Metrics/AreaAvailableLineChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/DensityBarChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/PopulationCategoryChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/PopulationEstimateCategory.tsx
  django_project/frontend/src/containers/MainPage/Metrics/PopulationEstimateCategoryAsPercentage.tsx
  django_project/frontend/src/containers/MainPage/Metrics/PropertyAvailable.tsx
  django_project/frontend/src/containers/MainPage/Metrics/PropertyType.tsx
  django_project/frontend/src/containers/MainPage/Metrics/SpeciesCountAsPercentage.tsx
  django_project/frontend/src/containers/MainPage/Metrics/TotalCountPerActivity.tsx
  django_project/frontend/src/containers/MainPage/Metrics/index.tsx
Labels: Size: 5, Fix, charts

#1309 Population trend graph
  django_project/frontend/api_views/statistical.py
  django_project/frontend/models/statistical.py
  django_project/frontend/serializers/metrics.py
  django_project/frontend/src/containers/MainPage/Metrics/PopulationTrend.tsx
  django_project/frontend/src/containers/MainPage/Metrics/index.tsx
  django_project/frontend/tests/test_species_population_trend.py
  django_project/frontend/urls.py
Labels: Size: 5, charts

#1303 Documentatin data upload
  docs/src/user/manual/data-upload/img/panel-1.png
  docs/src/user/manual/data-upload/img/panel-10.png
  docs/src/user/manual/data-upload/img/panel-11.png
  docs/src/user/manual/data-upload/img/panel-2.png
  docs/src/user/manual/data-upload/img/panel-3.png
  docs/src/user/manual/data-upload/img/panel-4.png
  docs/src/user/manual/data-upload/img/panel-5.png
  docs/src/user/manual/data-upload/img/panel-6.png
  docs/src/user/manual/data-upload/img/panel-7.png
  docs/src/user/manual/data-upload/img/panel-8.png
  docs/src/user/manual/data-upload/img/panel-9.png
  docs/src/user/manual/data-upload/panel.md
Labels: documentation, Size: 5

#1328 Chart updates
  django_project/frontend/api_views/statistical.py
  django_project/frontend/src/containers/MainPage/Metrics/AgeGroupBarChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/AreaAvailableLineChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/PopulationTrend.tsx
  django_project/frontend/src/containers/MainPage/Metrics/TotalCountPerActivity.tsx
  django_project/frontend/src/containers/MainPage/Metrics/index.tsx
  django_project/frontend/tests/test_species_population_trend.py
Labels: Size: 1, Fix

#1351 Update sidebar panel charts on map
  django_project/frontend/src/containers/MainPage/Metrics/ActivityBarChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/SpeciesSideBarLineChart.tsx
Labels: Size: 2, Fix

#1346 Documentation online form
  docs/src/user/manual/data-upload/img/online-form-1.png
  docs/src/user/manual/data-upload/img/online-form-2.png
  docs/src/user/manual/data-upload/img/online-form-3.png
  docs/src/user/manual/data-upload/img/online-form-4.png
  docs/src/user/manual/data-upload/img/online-form-5.png
  docs/src/user/manual/data-upload/online-form.md
Labels: documentation, Size: 8

#1357 patch: fix population trend graph
  django_project/frontend/src/containers/MainPage/Metrics/PopulationTrend.tsx
  django_project/frontend/src/containers/MainPage/Metrics/index.tsx
Labels: Size: 2, Fix

#1362 Update documentation link
  django_project/frontend/src/components/Footer/index.tsx
  django_project/frontend/templates/base.html
Labels: Size: 1, Implementation

#1300 E2E playwright tests
  .gitignore
  django_project/frontend/e2e/about.spec.ts
  django_project/frontend/e2e/contact.spec.ts
  django_project/frontend/e2e/fixtures/parcel.geojson
  django_project/frontend/e2e/help.spec.ts
  django_project/frontend/e2e/home.spec.ts
  django_project/frontend/package-lock.json
  django_project/frontend/package.json
  django_project/frontend/playwright.config.ts
Labels: ui testing

#1352 Change the order of all the charts bars
  django_project/frontend/src/containers/MainPage/Metrics/DensityBarChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/PopulationCategoryChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/PropertyAvailable.tsx
  django_project/frontend/src/containers/MainPage/Metrics/SpeciesCountPerProvinceChart.tsx
Labels: Size: 2, Fix

#1358 Update about page video
  django_project/frontend/templates/about.html
Labels: Size: 1

#1383 Adjust donut charts
  django_project/frontend/src/containers/MainPage/Metrics/ActivityCountAsPercentage.tsx
  django_project/frontend/src/containers/MainPage/Metrics/PopulationEstimateCategory.tsx
  django_project/frontend/src/containers/MainPage/Metrics/PopulationEstimateCategoryAsPercentage.tsx
  django_project/frontend/src/containers/MainPage/Metrics/SpeciesCountAsPercentage.tsx
  django_project/frontend/src/containers/MainPage/Metrics/TotalCountPerActivity.tsx
  django_project/frontend/src/containers/MainPage/Metrics/index.tsx
Labels: Size: 1, Fix, charts

#1379 Documentation for download data visualisation
  docs/src/user/manual/explore/charts.md
  docs/src/user/manual/explore/img/charts-1.png
  docs/src/user/manual/explore/img/charts-2.png
  docs/src/user/manual/explore/img/charts-3.png
Labels: documentation, Size: 2

#1398 Added links to the footer logos
  django_project/frontend/templates/base.html
Labels: Size: 1, Implementation

#1403 Ui fixes for popups
  django_project/frontend/static/css/style.css
  django_project/frontend/templates/account/account_inactive.html
  django_project/frontend/templates/account/forgot_password_reset.html
  django_project/frontend/templates/account/password_reset.html
Labels: Size: 3, Fix

#1404 Fix footer issue
  django_project/frontend/src/components/Footer/index.tsx
  django_project/frontend/templates/base.html
Labels: Size: 1, Fix

#1385 patch: update test for total area per property type #1363
  django_project/frontend/api_views/metrics.py
  django_project/frontend/src/containers/MainPage/Metrics/PropertyType.tsx
  django_project/frontend/tests/test_metrics.py
  django_project/frontend/utils/metrics.py
Labels: Size: 2, Fix, charts

#1348 feat: enforce user roles on charts #1181
  django_project/frontend/src/containers/MainPage/Metrics/index.tsx
  django_project/frontend/src/services/api.ts
Labels: Size: 3, charts

#1381 Documentation filter reports
  docs/src/user/manual/explore/img/reports-3.png
  docs/src/user/manual/explore/img/reports-4.png
  docs/src/user/manual/explore/img/reports-5.png
  docs/src/user/manual/explore/img/reports-6.png
  docs/src/user/manual/explore/img/reports-7.png
  docs/src/user/manual/explore/img/reports-8.png
  docs/src/user/manual/explore/reports.md
Labels: documentation, Size: 5

#1406 UI changes for the about page
  django_project/frontend/e2e/about.spec.ts
  django_project/frontend/templates/about.html
Labels: Size: 1, Implementation

#1424 UI login page
  django_project/frontend/static/js/bootstrap-4.3.1/css/bootstrap.css
  django_project/frontend/templates/account/login.html
  docs/src/user/manual/login-logout/img/login-page-1.png
  docs/src/user/manual/login-logout/login-page.md
Labels: documentation, Size: 1, Fix

#1425 Remove EXPLORE prior to login
  django_project/frontend/src/components/Footer/index.tsx
  django_project/frontend/templates/base.html
Labels: Size: 1, Implementation

#1454 Fix title issue
  django_project/frontend/templates/about.html
  django_project/frontend/templates/account/forgot_password_reset.html
  django_project/frontend/templates/account/login.html
  django_project/frontend/templates/account/logout.html
  django_project/frontend/templates/account/password_reset.html
  django_project/frontend/templates/account/signup.html
  django_project/frontend/templates/allauth_2fa/authenticate.html
  django_project/frontend/templates/base.html
  django_project/frontend/templates/contact.html
  django_project/frontend/templates/profile.html
  django_project/sawps/tests/test_user.py
Labels: Size: 2, Implementation

#1453 Changes error messages
  django_project/frontend/e2e/about.spec.ts
  django_project/frontend/templates/reminders.html
Labels: Size: 2, Implementation

#1410 Documentation about page
  django_project/frontend/src/components/Footer/index.tsx
  docs/src/user/manual/about.md
  docs/src/user/manual/img/about-page-1.png
  docs/src/user/manual/img/about-page-2.png
  docs/src/user/manual/img/about-page-3.png
  docs/src/user/manual/img/about-page-4.png
  docs/src/user/manual/img/about-page-5.png
  docs/src/user/manual/img/landing-page-4.png
  docs/src/user/manual/img/landing-page-5.png
  docs/src/user/manual/img/landing-page-6.png
  docs/src/user/manual/img/landing-page-7.png
  docs/src/user/manual/landing-page.md
Labels: documentation, Size: 2, Fix

#1475 Fix UI authentication page
  django_project/frontend/templates/about.html
  django_project/frontend/templates/allauth_2fa/authenticate.html
Labels: Size: 1, Implementation, Fix

#1484 Admin annualpopulation per activity UI
  django_project/population_data/admin.py
Labels: Size: 1, Django Admin Page

#1476 Feature add search in admin
  django_project/activity/admin.py
  django_project/frontend/admin.py
  django_project/frontend/src/components/Footer/index.tsx
  django_project/frontend/templates/base.html
  django_project/notification/admin.py
  django_project/occurrence/admin.py
  django_project/population_data/admin.py
  django_project/property/admin.py
  django_project/species/admin.py
  django_project/stakeholder/admin.py
Labels: enhancement, Size: 5, Django Admin Page

#1483 Annualpopulation UI
  django_project/population_data/admin.py
Labels: Size: 1, Django Admin Page
