Repository kartoza/sawps, pull requests merged in 2023-07, with the labels that each got.

#650 Feature organisation request
  django_project/frontend/templates/emails/invitation_email.html
  django_project/frontend/templates/emails/request_organisation_email.html
  django_project/frontend/templates/navibar.html
  django_project/frontend/templates/profile.html
  django_project/frontend/templates/users.html
  django_project/frontend/views/users.py
  django_project/sawps/views.py
  django_project/stakeholder/views.py
Labels: Implementation

#652 Fix broken tests
  .flake8
  .github/workflows/build-and-test.yml
  .vscode/tasks.json
  Makefile
  deployment/docker-compose.override.test.yml
  deployment/docker-compose.yml
  django_project/core/settings/contrib.py
  django_project/core/settings/dev.py
  django_project/frontend/filters/data_table.py
  django_project/frontend/package-lock.json
  django_project/frontend/tests/test_contact_us.py
  django_project/frontend/tests/test_data_table.py
  django_project/frontend/tests/test_users_view.py
  django_project/frontend/views/contact.py
  django_project/frontend/views/users.py
  django_project/initialize.py
  django_project/notification/tests.py
  django_project/notification/tests/reminder_factory.py
  django_project/notification/tests/test_api_views.py
  django_project/notification/views.py
  django_project/occurrence/factories.py
  django_project/occurrence/models.py
  django_project/population_data/factories.py
  django_project/population_data/models.py
  django_project/population_data/serializers.py
  django_project/population_data/test_population_data_models.py
  django_project/property/factories.py
  django_project/property/models.py
  django_project/property/test_property_models.py
  django_project/regulatory_permit/test_regulartory_permit_models.py
  django_project/sawps/admin.py
  django_project/sawps/forms/account_forms.py
  django_project/sawps/middleware.py
  django_project/sawps/password_validation.py
  django_project/sawps/views.py
  django_project/species/admin.py
  django_project/species/factories.py
  django_project/species/forms.py
  django_project/species/models.py
  django_project/species/test_species_models.py
  django_project/species/urls.py
  django_project/stakeholder/factories.py
  django_project/stakeholder/test_profile.py
  django_project/stakeholder/test_stakeholder_models.py
  django_project/stakeholder/views.py
Labels: draft

#655 Show coverage report
  .github/workflows/build-and-test.yml
  .vscode/launch.json
  deployment/docker-compose.override.test.yml
  django_project/fixtures/user_profile.json
  django_project/population_data/factories.py
  django_project/population_data/test_population_data_models.py
Labels: draft

#665 Update pre-commit run config
  .pre-commit-config.yaml
Labels: draft

#690 Fix pre-commit
  .pre-commit-config.yaml
Labels: draft

#691 Add codecov.yml
  .dockerignore
  .github/workflows/build-and-test.yml
  codecov.yml
  django_project/sawps/tests/__init__.py
  django_project/sawps/tests/models/__init__.py
  django_project/sawps/tests/test_user.py
Labels: draft

#686 Feature reminders page
  django_project/core/celery.py
  django_project/frontend/serializers/stakeholder.py
  django_project/frontend/templates/emails/reminder_email.html
  django_project/frontend/templates/profile_config_base.html
  django_project/frontend/templates/reminders.html
  django_project/stakeholder/admin.py
  django_project/stakeholder/migrations/0009_userprofile_received_notif_reminders.py
  django_project/stakeholder/models.py
  django_project/stakeholder/tasks.py
  django_project/stakeholder/test_profile.py
  django_project/stakeholder/test_stakeholder_models.py
  django_project/stakeholder/test_tasks.py
  django_project/stakeholder/test_view.py
  django_project/stakeholder/urls.py
  django_project/stakeholder/views.py
Labels: Size: 8, Implementation

#701 Feature forgot password
  django_project/core/settings/project.py
  django_project/frontend/templates/account/forgot_password_reset.html
  django_project/frontend/templates/account/password_reset.html
  django_project/frontend/templates/emails/password_reset.html
  django_project/sawps/tests/test_user.py
  django_project/sawps/urls.py
  django_project/sawps/views.py
Labels: Size: 3, Implementation

#704 patch: add forgot password link
  django_project/frontend/templates/account/login.html
Labels: Size: 1, Implementation

#706 Fix data table API
  django_project/frontend/src/containers/MainPage/Data/index.tsx
  django_project/population_data/serializers.py
Labels: bug

#708 Feature notifications
  django_project/frontend/static/images/icons/notif_bell.svg
  django_project/frontend/templates/about.html
  django_project/frontend/templates/account/account_inactive.html
  django_project/frontend/templates/account/login.html
  django_project/frontend/templates/account/logout.html
  django_project/frontend/templates/account/signup.html
  django_project/frontend/templates/allauth_2fa/authenticate.html
  django_project/frontend/templates/base.html
  django_project/frontend/templates/contact.html
  django_project/frontend/templates/help.html
  django_project/frontend/templates/navibar.html
  django_project/frontend/templates/users.html
  django_project/frontend/tests/base_view.py
  django_project/frontend/views/base_view.py
  django_project/frontend/views/users.py
Labels: Size: 5, Implementation

#707 Feature notifications page
  django_project/frontend/templates/notifications.html
  django_project/stakeholder/test_view.py
  django_project/stakeholder/urls.py
  django_project/stakeholder/views.py
Labels: Size: 5, Implementation

#709 Delete edit reminders notifications
  django_project/frontend/static/css/style.css
  django_project/frontend/templates/account/forgot_password_reset.html
  django_project/frontend/templates/account/password_reset.html
  django_project/frontend/templates/navibar.html
  django_project/frontend/templates/notifications.html
  django_project/frontend/templates/profile_config_base.html
  django_project/frontend/templates/reminders.html
  django_project/frontend/templates/users.html
  django_project/sawps/tests/test_user.py
  django_project/stakeholder/test_view.py
Labels: Size: 1, Implementation
