Repository kartoza/sawps, pull requests merged in 2023-08, with the labels that each got.

#714 Push notification functionality reminders
  deployment/docker-compose.yml
  django_project/frontend/templates/base.html
  django_project/frontend/templates/navibar.html
  django_project/frontend/templates/profile.html
  django_project/frontend/tests/base_view.py
  django_project/frontend/tests/test_notifications.py
  django_project/frontend/urls.py
  django_project/frontend/views/base_view.py
Labels: Size: 3, Implementation

#717 Feature reset 2fa
  django_project/frontend/serializers/totp_device.py
  django_project/frontend/templates/allauth_2fa/authenticate.html
  django_project/frontend/templates/allauth_2fa/backup_tokens.html
  django_project/frontend/templates/profile_config_base.html
  django_project/frontend/tests/test_2fa_view.py
  django_project/frontend/urls.py
  django_project/frontend/views/totp_device.py
Labels: Size: 5, Implementation

#723 Tinashechiraya push notification patch
  django_project/frontend/templates/about.html
  django_project/frontend/templates/base.html
  django_project/frontend/templates/navibar.html
Labels: Size: 1, Implementation

#738 Fixes for donut chart
  django_project/frontend/src/containers/MainPage/Metrics/ActivityDonutChart.tsx
Labels: bug, Size: 1

#732 Use case fixes
  deployment/docker-compose.yml
  django_project/frontend/static/css/style.css
  django_project/frontend/templates/about.html
  django_project/frontend/templates/account/account_inactive.html
  django_project/frontend/templates/account/forgot_password_reset.html
  django_project/frontend/templates/account/login.html
  django_project/frontend/templates/account/logout.html
  django_project/frontend/templates/account/password_reset.html
  django_project/frontend/templates/account/signup.html
  django_project/frontend/templates/allauth_2fa/authenticate.html
  django_project/frontend/templates/base.html
  django_project/frontend/templates/contact.html
  django_project/frontend/templates/help.html
  django_project/frontend/templates/navibar.html
  django_project/frontend/templates/profile.html
  django_project/stakeholder/test_email_exists.py
  django_project/stakeholder/test_profile.py
  django_project/stakeholder/urls.py
  django_project/stakeholder/views.py
Labels: Size: 5, Implementation

#725 Species Population Totals and Density
  django_project/frontend/api_views/metrics.py
  django_project/frontend/filters/metrics.py
  django_project/frontend/serializers/metrics.py
  django_project/frontend/src/containers/MainPage/Metrics/DensityBarChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/SpeciesLineChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/index.tsx
  django_project/frontend/tests/test_metrics.py
  django_project/frontend/urls.py
Labels: Size: 8, Pillar 3: wireframe, Implementation

#739 Styling fixes
  django_project/frontend/src/components/LandingPage/LandingPagePopulationOverview/styles.scss
  django_project/frontend/templates/about.html
  django_project/frontend/templates/contact.html
  django_project/frontend/templates/emails/reminder_email.html
  django_project/frontend/templates/help.html
  django_project/frontend/templates/navibar.html
  django_project/stakeholder/tasks.py
  django_project/stakeholder/test_tasks.py
Labels: bug, Size: 1

#740 Number of properties per population category
  django_project/frontend/api_views/metrics.py
  django_project/frontend/filters/metrics.py
  django_project/frontend/src/containers/MainPage/Metrics/PopulationCategoryChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/index.tsx
  django_project/frontend/tests/test_metrics.py
  django_project/frontend/urls.py
  django_project/frontend/utils/metrics.py
Labels: Size: 8, Pillar 3: wireframe, Implementation

#748 patch: flag true for notifications
  django_project/stakeholder/tasks.py
Labels: bug

#749 Add playwright testing
  .github/workflows/build-and-test.yml
  .gitignore
  Makefile
  deployment/.template.test.env
  deployment/docker-compose.override.test.yml
  deployment/docker/Dockerfile
  django_project/core/settings/test.py
  django_project/frontend/e2e/landingPage.spec.ts
  django_project/frontend/package-lock.json
  django_project/frontend/package.json
  django_project/frontend/playwright.config.ts
Labels: draft

#750 Update api speciesPopulationCount and integrate filters
  django_project/frontend/api_views/metrics.py
  django_project/frontend/filters/metrics.py
  django_project/frontend/serializers/metrics.py
  django_project/frontend/src/containers/MainPage/Metrics/ActivityDonutChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/DensityBarChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/PopulationCategoryChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/SpeciesLineChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/index.scss
  django_project/frontend/src/containers/MainPage/Metrics/index.tsx
  django_project/frontend/tests/test_metrics.py
  django_project/frontend/urls.py
Labels: Size: 8, Pillar 3: wireframe, Implementation

#757 Tinashechiraya patch 2
  django_project/frontend/templates/base.html
  django_project/frontend/templates/profile_config_base.html
  django_project/frontend/views/base_view.py
  django_project/stakeholder/tasks.py
  django_project/stakeholder/test_profile.py
  django_project/stakeholder/test_tasks.py
  django_project/stakeholder/test_view.py
  django_project/stakeholder/views.py
Labels: bug, Size: 1

#758 Update UI
  django_project/frontend/api_views/metrics.py
  django_project/frontend/serializers/metrics.py
  django_project/frontend/src/containers/MainPage/Metrics/ActivityDonutChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/DensityBarChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/PopulationCategoryChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/SpeciesLineChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/index.scss
  django_project/frontend/src/containers/MainPage/Metrics/index.tsx
  django_project/frontend/tests/test_metrics.py
Labels: Implementation

#773 feat: implement property sidebar #745
  django_project/frontend/src/components/PropertySummaryTable/index.tsx
  django_project/frontend/src/containers/MainPage/Map/index.tsx
  django_project/frontend/src/containers/MainPage/Metrics/ActivityBarChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/SpeciesSideBarLineChart.tsx
  django_project/frontend/src/containers/MainPage/Property/PropertySummary.tsx
  django_project/frontend/src/containers/MainPage/Property/index.scss
  django_project/frontend/templates/notifications.html
  django_project/frontend/templates/users.html
  django_project/frontend/views/users.py
  django_project/sawps/views.py
  django_project/stakeholder/test_profile.py
  django_project/stakeholder/test_view.py
  django_project/stakeholder/views.py
Labels: Size: 5, Implementation

#775 Feature user docs
  docs/src/user/2FA/instructions.md
  docs/src/user/forgot_password/instructions.md
  docs/src/user/img/add_device.png
  docs/src/user/img/add_reminder.png
  docs/src/user/img/delete_modal.png
  docs/src/user/img/delete_organization_member.png
  docs/src/user/img/delete_reminder.png
  docs/src/user/img/edit_reminder.png
  docs/src/user/img/email_sent_instructions.png
  docs/src/user/img/forgot_password_link.png
  docs/src/user/img/invitation_email.png
  docs/src/user/img/invitation_sent.png
  docs/src/user/img/new_member_reg_via_invite.png
  docs/src/user/img/notfications_page.png
  docs/src/user/img/notification_modal.png
  docs/src/user/img/notifications.png
  docs/src/user/img/organisation_members_link.png
  docs/src/user/img/organisation_members_page.png
  docs/src/user/img/organisation_request_form.png
  docs/src/user/img/organisation_request_sent.png
  docs/src/user/img/password_reset.png
  docs/src/user/img/password_reset_success.png
  docs/src/user/img/profile_2fa.png
  docs/src/user/img/qr_image.png
  docs/src/user/img/reminders_page.png
  docs/src/user/img/request_organisation_link.png
  docs/src/user/img/reset_password_email.png
  docs/src/user/img/reset_password_form.png
  docs/src/user/img/send_organisation_invite.png
  docs/src/user/notifications/instructions.md
  docs/src/user/organisation_members/instructions.md
  docs/src/user/organisation_request/instructions.md
  docs/src/user/reminders/instructions.md
Labels: documentation, Size: 8

#778 Integration area available to species
  django_project/frontend/api_views/metrics.py
  django_project/frontend/src/containers/MainPage/Metrics/PropertyAvailable.tsx
  django_project/frontend/src/containers/MainPage/Metrics/index.tsx
  django_project/frontend/tests/test_metrics.py
  django_project/frontend/urls.py
  django_project/frontend/utils/metrics.py
  django_project/species/factories.py
Labels: Size: 5, Pillar 3: wireframe, Implementation

#776 integration property type chart
  django_project/frontend/api_views/metrics.py
  django_project/frontend/src/containers/MainPage/Metrics/PropertyType.tsx
  django_project/frontend/src/containers/MainPage/Metrics/index.tsx
  django_project/frontend/tests/test_metrics.py
  django_project/frontend/urls.py
  django_project/frontend/utils/metrics.py
Labels: Size: 5, Pillar 3: wireframe, Implementation

#811 Integration editable year function
  django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
  django_project/frontend/src/containers/MainPage/SideBar/index.scss
  django_project/frontend/src/reducers/SpeciesFilter.ts
  django_project/frontend/tests/test_metrics.py
Labels: Implementation

#817 Org in profile and url
  django_project/frontend/src/containers/MainPage/MainPage.tsx
  django_project/frontend/templates/navibar.html
  django_project/stakeholder/test_profile.py
  django_project/stakeholder/views.py
Labels: Size: 5, Implementation

#802 Patch ecosystem type org page
  django_project/frontend/src/components/PropertySummaryTable/index.tsx
  django_project/frontend/tests/test_users_view.py
  django_project/frontend/views/users.py
Labels: bug, Size: 2

#820 Fixes for editable chart
  django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
Labels: bug, Size: 1

#824 patch: capitalisation of notification #809
  django_project/frontend/templates/notifications.html
Labels: Size: 1, Implementation

#819 Fix density chart
  django_project/frontend/api_views/metrics.py
  django_project/frontend/filters/metrics.py
  django_project/frontend/serializers/metrics.py
  django_project/frontend/src/containers/MainPage/Metrics/DensityBarChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/PropertyAvailable.tsx
  django_project/frontend/tests/test_metrics.py
  django_project/frontend/urls.py
  django_project/frontend/utils/metrics.py
Labels: bug, Size: 3

#846 Fix css
  django_project/frontend/src/containers/MainPage/Metrics/index.scss
  django_project/frontend/src/containers/MainPage/SideBar/index.scss
  django_project/frontend/src/containers/MainPage/SideBar/tab.scss
  django_project/frontend/src/containers/MainPage/index.scss
Labels: Size: 1, Implementation

#847 Fix activity percentage chart
  django_project/frontend/api_views/metrics.py
  django_project/frontend/serializers/metrics.py
  django_project/frontend/src/containers/MainPage/Metrics/ActivityDonutChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/index.tsx
  django_project/frontend/static_mapping.py
  django_project/frontend/tests/test_metrics.py
  django_project/frontend/utils/metrics.py
Labels: Size: 3, Implementation

#859 Forgot password cleanup
  django_project/frontend/templates/account/forgot_password_reset.html
  django_project/frontend/templates/account/password_reset.html
  django_project/sawps/tests/test_user.py
  django_project/sawps/views.py
Labels: Size: 1, Implementation

#860 Property sidebar improvements
  django_project/frontend/src/components/PropertySummaryTable/index.tsx
  django_project/frontend/src/containers/MainPage/Metrics/SpeciesSideBarLineChart.tsx
  django_project/frontend/src/containers/MainPage/Property/index.scss
Labels: Size: 1, Implementation

#862 patch: user menu clean ups #828
  django_project/frontend/templates/navibar.html
Labels: Size: 1, Fix

#865 patch: resolve key error
  django_project/frontend/views/base_view.py
Labels: Size: 1, Fix

#867 Feature age group chart
  django_project/frontend/api_views/metrics.py
  django_project/frontend/serializers/metrics.py
  django_project/frontend/src/containers/MainPage/Metrics/AgeGroupBarChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/index.scss
  django_project/frontend/src/containers/MainPage/Metrics/index.tsx
  django_project/frontend/tests/test_metrics.py
  django_project/frontend/urls.py
Labels: Size: 8, Pillar 3: wireframe, Implementation

#863 Add map styles for national
  django_project/frontend/src/containers/MainPage/Map/index.tsx
  django_project/frontend/templates/base.html
  django_project/frontend/templates/navibar.html
  django_project/frontend/tests/test_map.py
  django_project/frontend/utils/country_level_dark_v1.json
  django_project/frontend/utils/country_level_light_v1.json
  django_project/frontend/utils/map.py
Labels: Size: 5, Implementation

#873 Added female colour with transparency
  django_project/frontend/serializers/metrics.py
  django_project/frontend/src/containers/MainPage/Metrics/AgeGroupBarChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/index.tsx
Labels: Implementation

#885 Update icon field
  django_project/frontend/serializers/metrics.py
  django_project/frontend/src/containers/MainPage/Metrics/ActivityDonutChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/index.tsx
Labels: Size: 1, Implementation

#883 patch: update reset password text
  django_project/frontend/templates/account/password_reset.html
Labels: Size: 1, Fix

#896 patch: use user id instead
  django_project/frontend/views/base_view.py
Labels: Size: 1, Fix

#869 Integration feature area line chart
  django_project/frontend/api_views/metrics.py
  django_project/frontend/serializers/metrics.py
  django_project/frontend/src/containers/MainPage/Metrics/ActivityDonutChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/AreaAvailableLineChart.tsx
  django_project/frontend/src/containers/MainPage/Metrics/index.scss
  django_project/frontend/src/containers/MainPage/Metrics/index.tsx
  django_project/frontend/static_mapping.py
  django_project/frontend/tests/test_metrics.py
  django_project/frontend/urls.py
  django_project/species/factories.py
Labels: Size: 8, Pillar 3: wireframe, Implementation

#870 National report pdf page 1
  django_project/frontend/api_views/national_statistic.py
  django_project/frontend/package-lock.json
  django_project/frontend/package.json
  django_project/frontend/serializers/national_statistics.py
  django_project/frontend/src/components/PdfReport/CustomFirstPageCard.tsx
  django_project/frontend/src/components/PdfReport/FirstPageContent.tsx
  django_project/frontend/src/components/PdfReport/SANBI-logo.jpg
  django_project/frontend/src/components/PdfReport/generateChartImage.tsx
  django_project/frontend/src/components/PdfReport/index.scss
  django_project/frontend/src/components/PdfReport/index.tsx
  django_project/frontend/src/components/PdfReport/logoImage.d.ts
  django_project/frontend/src/components/PdfReport/sanbi_maps.jpg
  django_project/frontend/src/components/PdfReport/styles.scss
  django_project/frontend/src/containers/MainPage/Metrics/index.tsx
  django_project/frontend/tests/test_national_statistics.py
  django_project/frontend/tsconfig.json
  django_project/frontend/urls.py
  django_project/frontend/webpack.config.js
Labels: Size: 8, Implementation

#905 patch: prevent TypeError includes on null #777
  django_project/frontend/src/components/LandingPage/LandingPagePopulationOverview/SpeciesChart/index.tsx
Labels: Size: 1, Fix

#906 patch: prevent noneType object has not attribute 'name'
  django_project/frontend/api_views/statistical.py
Labels: Size: 1, Fix
