Repository kartoza/sawps, pull requests merged in 2023-11, with the labels that each got.

#1489 Fix annualpopulation issue
  django_project/population_data/admin.py
Labels: bug, Size: 1

#1435 Documentation for layers
  docs/src/user/manual/explore/img/layers-1.png
  docs/src/user/manual/explore/img/layers-10.png
  docs/src/user/manual/explore/img/layers-11.png
  docs/src/user/manual/explore/img/layers-12.png
  docs/src/user/manual/explore/img/layers-2.png
  docs/src/user/manual/explore/img/layers-3.png
  docs/src/user/manual/explore/img/layers-4.png
  docs/src/user/manual/explore/img/layers-5.png
  docs/src/user/manual/explore/img/layers-6.png
  docs/src/user/manual/explore/img/layers-7.png
  docs/src/user/manual/explore/img/layers-8.png
  docs/src/user/manual/explore/img/layers-9.png
  docs/src/user/manual/explore/layers.md
Labels: documentation, Size: 8

#1517 Make title same for all pages
  django_project/frontend/templates/about.html
  django_project/frontend/templates/account/account_inactive.html
  django_project/frontend/templates/account/forgot_password_reset.html
  django_project/frontend/templates/account/login.html
  django_project/frontend/templates/account/logout.html
  django_project/frontend/templates/account/password_change.html
  django_project/frontend/templates/account/password_reset.html
  django_project/frontend/templates/account/signup.html
  django_project/frontend/templates/allauth_2fa/authenticate.html
  django_project/frontend/templates/allauth_2fa/backup_tokens.html
  django_project/frontend/templates/allauth_2fa/setup.html
  django_project/frontend/templates/contact.html
  django_project/frontend/templates/help.html
  django_project/frontend/templates/notifications.html
  django_project/frontend/templates/online_form.html
  django_project/frontend/templates/organisations.html
  django_project/frontend/templates/profile.html
  django_project/frontend/templates/reminders.html
  django_project/frontend/templates/users.html
Labels: Size: 1, Fix

#1492 Documentation admin panel
  docs/src/administrator/manual/django-add-data.md
  docs/src/administrator/manual/django-admin.md
  docs/src/administrator/manual/django-change-data.md
  docs/src/administrator/manual/django-table.md
  docs/src/administrator/manual/img/admin-11.png
  docs/src/administrator/manual/img/admin-2.png
  docs/src/administrator/manual/img/admin-3.png
  docs/src/administrator/manual/img/admin-4.png
  docs/src/administrator/manual/img/admin-8.png
  docs/src/administrator/manual/img/admin-9.png
  docs/src/administrator/manual/img/django-add-data-1.png
  docs/src/administrator/manual/img/django-add-data-2.png
  docs/src/administrator/manual/img/django-add-data-3.png
  docs/src/administrator/manual/img/django-change-data-1.png
  docs/src/administrator/manual/img/django-change-data-2.png
  docs/src/administrator/manual/img/django-change-data-3.png
  docs/src/administrator/manual/img/django-change-data-4.png
  docs/src/administrator/manual/img/django-table-1.png
  docs/src/administrator/manual/img/django-table-2.png
  docs/src/administrator/manual/img/django-table-3.png
Labels: Size: 8, Django Admin Page

#1482 Documentation for 2FA
  docs/src/user/manual/register/img/setup-2fa-1.png
  docs/src/user/manual/register/img/setup-2fa-2.png
  docs/src/user/manual/register/img/setup-2fa-3.png
  docs/src/user/manual/register/img/setup-2fa-4.png
  docs/src/user/manual/register/img/setup-2fa-5.png
  docs/src/user/manual/register/img/setup-2fa-6.png
  docs/src/user/manual/register/setup-2fa.md
  playwright/ci-test/tests/about.spec.ts
Labels: documentation, Size: 3

#1499 Standardised docs
  docs/src/user/manual/about.md
  docs/src/user/manual/data-upload/online-form.md
  docs/src/user/manual/data-upload/panel.md
  docs/src/user/manual/data-upload/template-upload.md
  docs/src/user/manual/explore/charts.md
  docs/src/user/manual/explore/filters.md
  docs/src/user/manual/explore/map.md
  docs/src/user/manual/explore/reports.md
  docs/src/user/manual/help-contact.md
  docs/src/user/manual/landing-page.md
  docs/src/user/manual/login-logout/forgot-password.md
  docs/src/user/manual/login-logout/login-2fa-page.md
  docs/src/user/manual/login-logout/login-page.md
  docs/src/user/manual/login-logout/logout.md
  docs/src/user/manual/register/register-page.md
  docs/src/user/manual/user-profile/2fa.md
  docs/src/user/manual/user-profile/notifications.md
  docs/src/user/manual/user-profile/organisation-page.md
  docs/src/user/manual/user-profile/reminders.md
  docs/src/user/manual/user-profile/request-organisation.md
  docs/src/user/manual/user-roles.md
Labels: documentation, Size: 5

#1539 Documentation user table admin
  docs/src/administrator/manual/django-add-data.md
  docs/src/administrator/manual/django-change-data.md
  docs/src/administrator/manual/django-table.md
  docs/src/administrator/manual/img/django-add-data-4.png
  docs/src/administrator/manual/img/django-add-data-5.png
  docs/src/administrator/manual/img/django-add-data-6.png
  docs/src/administrator/manual/img/django-add-data-7.png
  docs/src/administrator/manual/img/django-add-data-8.png
  docs/src/administrator/manual/img/django-change-data-5.png
  docs/src/administrator/manual/img/django-change-data-6.png
  docs/src/administrator/manual/img/django-change-data-7.png
  docs/src/administrator/manual/img/django-change-data-8.png
  docs/src/administrator/manual/img/django-table-4.png
  docs/src/administrator/manual/img/django-table-5.png
Labels: documentation, Size: 3

#1544 Updated testing docs
  docs/src/developer/guide/img/testing-continuous-intergration-5.png
  docs/src/developer/guide/testing.md
Labels: documentation

#1573 Documentation for province report
  docs/src/user/manual/explore/img/reports-9.png
  docs/src/user/manual/explore/reports.md
Labels: Size: 1

#1678 Fix footer
  django_project/frontend/static/css/style.css
Labels: Size: 1, Fix

#1545 Documentation totp device
  docs/src/administrator/manual/django-add-data.md
  docs/src/administrator/manual/django-change-data.md
  docs/src/administrator/manual/django-table.md
  docs/src/administrator/manual/img/django-add-data-10.png
  docs/src/administrator/manual/img/django-add-data-9.png
  docs/src/administrator/manual/img/django-change-data-10.png
  docs/src/administrator/manual/img/django-change-data-9.png
  docs/src/administrator/manual/img/django-table-6.png
  docs/src/administrator/manual/img/django-table-7.png
Labels: documentation, Size: 3, Django Admin Page

#1647 Update screenshots login
  docs/src/user/manual/login-logout/forgot-password.md
  docs/src/user/manual/login-logout/img/forgot-password-1.png
  docs/src/user/manual/login-logout/img/forgot-password-2.png
  docs/src/user/manual/login-logout/img/forgot-password-3.png
  docs/src/user/manual/login-logout/img/forgot-password-5.png
  docs/src/user/manual/login-logout/img/forgot-password-6.png
  docs/src/user/manual/login-logout/img/login-2fa-page-1.png
  docs/src/user/manual/login-logout/img/login-page-1.png
  docs/src/user/manual/login-logout/login-2fa-page.md
  docs/src/user/manual/login-logout/login-page.md
Labels: documentation, Size: 1, Django Admin Page

#1560 Documentation admin tables
  docs/src/administrator/manual/django-admin.md
  docs/src/administrator/manual/img/admin-11.png
  docs/src/administrator/manual/img/admin-12.png
  docs/src/administrator/manual/img/admin-13.png
  docs/src/administrator/manual/img/admin-14.png
  docs/src/administrator/manual/img/admin-15.png
Labels: documentation, Size: 5, Django Admin Page

#1641 Update filter documentation
  docs/src/user/manual/explore/filters.md
  docs/src/user/manual/explore/img/filters-2.png
  docs/src/user/manual/explore/img/filters-4.png
  docs/src/user/manual/explore/img/filters-5.png
  docs/src/user/manual/explore/img/filters-6.png
  docs/src/user/manual/explore/img/filters-8.png
Labels: documentation, Size: 1, Django Admin Page

#1645 Documentation for Taxon table
  django_project/frontend/static/images/Loxodonta_africana-icon.svg
  docs/src/administrator/manual/django-add-data.md
  docs/src/administrator/manual/django-change-data.md
  docs/src/administrator/manual/django-table.md
  docs/src/administrator/manual/img/django-add-data-11.png
  docs/src/administrator/manual/img/django-add-data-12.png
  docs/src/administrator/manual/img/django-add-data-13.png
  docs/src/administrator/manual/img/django-add-data-14.png
  docs/src/administrator/manual/img/django-change-data-11.png
  docs/src/administrator/manual/img/django-table-8.png
Labels: documentation, Size: 3, Django Admin Page

#1591 Tests
  .github/workflows/build-and-test.yml
  Makefile
  deployment/.template.test.env
  deployment/docker-compose.override.test.yml
  django_project/fixtures/count_method.json
  playwright/ci-test/.envrc
  playwright/ci-test/.gitignore
  playwright/ci-test/README.md
  playwright/ci-test/base-url.sh
  playwright/ci-test/create-auth.sh
  playwright/ci-test/fixtures/parcel.geojson
  playwright/ci-test/nodesource-install.sh
  playwright/ci-test/playwright-path.sh
  playwright/ci-test/playwright.config.ts
  playwright/ci-test/record-test.sh
  playwright/ci-test/run-tests.sh
  playwright/ci-test/shell.nix
  playwright/ci-test/tests/active-user.spec.ts
  playwright/ci-test/tests/auth.setup.ts
  playwright/ci-test/tests/contact.spec.ts
  playwright/ci-test/tests/filters.spec.ts
  playwright/ci-test/tests/fixtures/parcel.geojson
  playwright/ci-test/tests/map.spec.ts
  playwright/ci-test/tests/upload-file.spec.ts
Labels: ui testing

#1652 Update register user profile docs
  django_project/frontend/static/css/style.css
  docs/src/user/manual/register/img/setup-2fa-1.png
  docs/src/user/manual/register/img/setup-2fa-2.png
  docs/src/user/manual/register/img/setup-2fa-3.png
  docs/src/user/manual/register/img/setup-2fa-4.png
  docs/src/user/manual/register/img/setup-2fa-5.png
  docs/src/user/manual/register/img/setup-2fa-6.png
  docs/src/user/manual/register/setup-2fa.md
  docs/src/user/manual/user-profile/img/notifications-1.png
  docs/src/user/manual/user-profile/img/organisation-page-2.png
  docs/src/user/manual/user-profile/img/profile-picture-upload.png
  docs/src/user/manual/user-profile/img/profile.png
  docs/src/user/manual/user-profile/img/request-organisation-1.png
  docs/src/user/manual/user-profile/img/request-organisation-2.png
  docs/src/user/manual/user-profile/img/request-organisation-3.png
  docs/src/user/manual/user-profile/notifications.md
  docs/src/user/manual/user-profile/organisation-page.md
  docs/src/user/manual/user-profile/profile-page.md
  docs/src/user/manual/user-profile/request-organisation.md
Labels: documentation, Size: 3

#1658 Update user role documentation
  docs/src/user/manual/user-roles.md
Labels: documentation, Size: 1

#1671 Update map doc
  docs/src/user/manual/explore/map.md
Labels: documentation, Size: 2

#1734 Added more content in map doc
  docs/src/user/manual/explore/img/map-1.png
  docs/src/user/manual/explore/img/map-2.png
  docs/src/user/manual/explore/img/map-3.png
  docs/src/user/manual/explore/img/map-4.png
  docs/src/user/manual/explore/img/map-5.png
  docs/src/user/manual/explore/img/map-6.png
  docs/src/user/manual/explore/img/map-7.png
  docs/src/user/manual/explore/map.md
Labels: documentation, Size: 3

#1728 Add missing mkdocstring
  django_project/frontend/api_views/metrics.py
  django_project/frontend/api_views/national_statistic.py
  django_project/frontend/tests/test_national_statistics.py
  django_project/frontend/views/base_view.py
  django_project/frontend/views/switch_organisation.py
  django_project/stakeholder/tests/test_view.py
  docs/src/developer/manual/activity.md
  docs/src/developer/manual/frontend.md
  docs/src/developer/manual/population_data.md
  docs/src/developer/manual/property.md
  docs/src/developer/manual/regulator_permit.md
  docs/src/developer/manual/sawps.md
  docs/src/developer/manual/species.md
  docs/src/developer/manual/stakeholder.md
  docs/src/user/guide/organisations.md
Labels: Size: 3, developer documentation
