Repository kartoza/sawps, pull requests merged in 2024-01, with the labels that each got.

#1885 Correct typos and minor changes
  docs/src/user/manual/about.md
  docs/src/user/manual/data-upload/index.md
  docs/src/user/manual/data-upload/panel.md
  docs/src/user/manual/explore/layers.md
  docs/src/user/manual/explore/trends.md
  docs/src/user/manual/help-contact.md
  docs/src/user/manual/index.md
  docs/src/user/manual/landing-page.md
  docs/src/user/manual/login-logout/forgot-password.md
  docs/src/user/manual/register/register-page.md
  docs/src/user/manual/user-profile/2fa.md
  docs/src/user/manual/user-profile/index.md
  docs/src/user/manual/user-profile/notifications.md
  docs/src/user/manual/user-profile/organisation-page.md
  docs/src/user/manual/user-profile/reminders.md
Labels: documentation, Size: 2

#1895 Added note for uploading file on windows
  docs/src/user/manual/explore/trends.md
Labels: documentation, Size: 1

#1896 Update the online form first step fields doc
  docs/src/user/manual/data-upload/img/online-form-6.png
  docs/src/user/manual/data-upload/img/online-form-7.png
  docs/src/user/manual/data-upload/online-form.md
Labels: documentation, Size: 2

#1893 Update upload parcel doc
  docs/src/user/manual/data-upload/panel.md
Labels: documentation, Size: 1

#1912 Added testing videos in docs
  docs/src/about/img/naming_convention.README
  docs/src/about/img/testing-videos-playlist-1.png
  docs/src/about/index.md
Labels: documentation, Size: 1

#1892 Documentation: Corrections
  docs/mkdocs-base.yml
  docs/mkdocs-html.yml
  docs/src/about/index.md
  docs/src/developer/api/guide/index.md
  docs/src/developer/api/index.md
  docs/src/developer/api/manual/index.md
  docs/src/developer/index.md
  docs/src/user/guide/data-upload.md
  docs/src/user/guide/img/upload-data-message-1.png
  docs/src/user/guide/img/upload-data-message-2.png
  docs/src/user/guide/img/upload-data-message-3.png
  docs/src/user/guide/img/upload-data-message-4.png
  docs/src/user/guide/img/upload-data-new-11-2.png
  docs/src/user/guide/img/upload-data-new-11-3.png
  docs/src/user/manual/data-upload/img/panel-7-2.png
  docs/src/user/manual/data-upload/img/panel-7.png
  docs/src/user/manual/data-upload/img/upload-data-message-1.png
  docs/src/user/manual/data-upload/img/upload-data-message-2.png
  docs/src/user/manual/data-upload/img/upload-data-message-3.png
  docs/src/user/manual/data-upload/img/upload-data-message-4.png
  docs/src/user/manual/data-upload/panel.md
  docs/src/user/manual/explore/charts.md
  docs/src/user/manual/explore/filters.md
  docs/src/user/manual/explore/trends.md
  docs/src/user/manual/landing-page.md
  docs/src/user/manual/user-profile/2fa.md
  docs/src/videos/img/naming_convention.README
  docs/src/videos/img/testing-videos-playlist-1.png
  docs/src/videos/index.md
Labels: documentation
