Repository kartoza/sawps, pull requests merged in 2024-03, with the labels that each got.

#2000 Update layers manual
  docs/src/user/manual/explore/img/layers-10.png
  docs/src/user/manual/explore/img/layers-11.png
  docs/src/user/manual/explore/img/layers-13.png
  docs/src/user/manual/explore/img/layers-14.png
  docs/src/user/manual/explore/img/layers-3.png
  docs/src/user/manual/explore/img/layers-4.png
  docs/src/user/manual/explore/img/layers-5.png
  docs/src/user/manual/explore/img/layers-6.png
  docs/src/user/manual/explore/img/layers-7.png
  docs/src/user/manual/explore/img/layers-8.png
  docs/src/user/manual/explore/img/layers-9.png
  docs/src/user/manual/explore/layers.md
Labels: documentation, Size: 2

#2005 Update screenshots
  docs/src/user/guide/img/logging-in-2.png
  docs/src/user/guide/img/logging-in-3.png
Labels: documentation, Size: 1

#2015 Update the user manual
  docs/src/user/guide/data-upload.md
  docs/src/user/guide/img/upload-data-existing-1.png
  docs/src/user/guide/img/upload-data-existing-2.png
  docs/src/user/guide/img/upload-data-existing-3.png
  docs/src/user/guide/img/upload-data-existing-4.png
  docs/src/user/guide/img/upload-data-new-10.png
  docs/src/user/guide/img/upload-data-new-12.png
  docs/src/user/guide/img/upload-data-new-13.png
  docs/src/user/guide/img/upload-data-new-14.png
  docs/src/user/guide/img/upload-data-new-15.png
  docs/src/user/guide/img/upload-data-new-16.png
  docs/src/user/guide/img/upload-data-new-17.png
  docs/src/user/guide/img/upload-data-new-19.png
  docs/src/user/guide/img/upload-data-new-25.png
  docs/src/user/guide/img/upload-data-new-3.png
  docs/src/user/guide/img/upload-data-new-4.png
  docs/src/user/guide/img/upload-data-new-5.png
  docs/src/user/guide/img/upload-data-new-6.png
  docs/src/user/guide/img/upload-data-new-7.png
  docs/src/user/guide/img/upload-data-new-8.png
  docs/src/user/guide/img/upload-data-new-9.png
Labels: documentation, Size: 8

#2016 Update landing page manual
  docs/src/user/manual/img/landing-page-2.png
  docs/src/user/manual/img/landing-page-4.png
  docs/src/user/manual/img/landing-page-8.png
  docs/src/user/manual/img/landing-page-9.png
  docs/src/user/manual/landing-page.md
Labels: documentation, Size: 1

#2019 Update quickstart screenshot
  docs/src/user/quickstart/img/logging-in-2.png
  docs/src/user/quickstart/img/logging-in-3.png
Labels: documentation, Size: 1

#2020 Update the screenshots and change the document according to the new UI
  docs/src/user/manual/data-upload/img/panel-1.png
  docs/src/user/manual/data-upload/img/panel-10.png
  docs/src/user/manual/data-upload/img/panel-11.png
  docs/src/user/manual/data-upload/img/panel-12.png
  docs/src/user/manual/data-upload/img/panel-13.png
  docs/src/user/manual/data-upload/img/panel-2.png
  docs/src/user/manual/data-upload/img/panel-3.png
  docs/src/user/manual/data-upload/img/panel-4.png
  docs/src/user/manual/data-upload/img/panel-5.png
  docs/src/user/manual/data-upload/img/panel-6.png
  docs/src/user/manual/data-upload/img/panel-7-2.png
  docs/src/user/manual/data-upload/img/panel-7.png
  docs/src/user/manual/data-upload/img/panel-8.png
  docs/src/user/manual/data-upload/img/panel-9.png
  docs/src/user/manual/data-upload/img/upload-data-message-1.png
  docs/src/user/manual/data-upload/img/upload-data-message-2.png
  docs/src/user/manual/data-upload/panel.md
Labels: documentation, Size: 8

#1924 Docs: PDF generation updates and build fixes
  .gitignore
  docs/assets/logo-sanbi.svg
  docs/mkdocs-base.yml
  docs/mkdocs-pdf.yml
  docs/src/administrator/guide/manage-taxa.md
  docs/src/administrator/index.md
  docs/src/administrator/manual/index.md
  docs/src/developer/guide/design.md
  docs/src/developer/index.md
  docs/src/developer/manual/population_data.md
  docs/src/devops/guide/index.md
  docs/src/devops/index.md
  docs/src/index.md
  docs/src/user/guide/registering.md
  docs/src/user/index.md
  docs/src/user/manual/data-upload/index.md
  docs/src/user/manual/explore/index.md
  docs/src/user/manual/help-contact.md
  docs/src/user/manual/index.md
  docs/src/user/manual/login-logout/forgot-password.md
  docs/src/user/manual/login-logout/index.md
  docs/src/user/manual/login-logout/login-page.md
  docs/src/user/manual/register/index.md
  docs/src/user/quickstart/index.md
  docs/src/videos/index.md
  docs/templates/IDS_Logo.svg
  docs/templates/IDS_footer.svg
  docs/templates/cover.html
  docs/templates/graphics.scss
  docs/templates/graphics.scss.templ
  docs/templates/styles.scss
  docs/templates/variables.scss
  requirements.txt
Labels: documentation
